### ISSUE TITLE
Errors on no changes

### ISSUE THREAD

**Issue by N6REJ** [GuillaumeFalourd/git-commit-push#1]
If nothing has been modified it throws an error instead of quietly exiting
https://github.com/Bearsampp/.settings/blob/main/.github/workflows/list-repos.yml

**Comment by GuillaumeFalourd** [comment]
Hi @N6REJ , thank you for your feedback! 👍🏼 

I didn't expected this behavior in the implementation, I'll think about a solution and update the action ASAP 😄

**Comment by GuillaumeFalourd** [comment]
I've updated the action, if you want to test it using the `@main` instead of `@v1`, I would be happy to receive more feedbacks! Now, if the `git status --porcelain` is empty, the action will be aborted and not commit / push any file, just giving a WARNING to the user.
