### ISSUE TITLE
[Question] Action fails if not on main branch

### ISSUE THREAD

**Issue by ayushmanchhabra** [GuillaumeFalourd/git-commit-push#6]
I'm running into an error:
https://github.com/tharatau/idea-maze/actions/runs/3963315913/jobs/6791006026

Here's my config file:
https://github.com/tharatau/idea-maze/blob/522ae6ec1e6f966276ca4d533cee766652877122/.github/workflows/nw-toolkit.yml

My intuition is I'm configuring it incorrectly. What am I missing?

**Comment by ayushmanchhabra** [comment]
Okay turns out it was not working on a branch but it worked on `main`.

**Comment by GuillaumeFalourd** [comment]
Hi @tharatau. Thank you for opening this issue! 👍🏼 

It should work as expected, even on different branch, if you run the workflow as you implemented.

A few questions:
1. Did you try informing the branch as action input?
2. What was the workflow implementation for pushing and committing the code to another branch?

**Comment by ayushmanchhabra** [comment]
I'll try to come up with a test case.

**Comment by ayushmanchhabra** [comment]
Here's what I was initially trying to do:
https://github.com/tharatau/idea-maze/pull/7

> Did you try informing the branch as action input?

Not sure what you mean?

**Comment by GuillaumeFalourd** [comment]
Hmm, I forked your repo and made some tests, but didn't understand why the updated file isn't identified yet.

I believe it might happen in the case of a `pull_request` event, as the when you can create a pull request, Github will execute workflow based on a fake merge branch: `refs/pull/:prNumber/merge`.

> Not sure what you mean?

It's what you did by informing the branch to push to.

**Comment by ayushmanchhabra** [comment]
I looked into the docs. This might be a limitation of Git/GitHub since:

> Github will execute workflow based on a fake merge branch

I'm happy with my current implementation. This can be closed as `wontfix` or similar. Leaving that up to you.

Thanks!

**Comment by GuillaumeFalourd** [comment]
Ok. Thank you for the return 😄 
Let's see if we'll have an opportunity to improve this behavior in the future!
